<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Tropicast.Station</AssemblyName>
    <RootNamespace>Tropicast.Station.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\tropicast.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tropicast.Station.Core\Tropicast.Station.Core.csproj" />
    <ProjectReference Include="..\Tropicast.Station.Audio\Tropicast.Station.Audio.csproj" />
    <ProjectReference Include="..\Tropicast.Station.Audio.Windows\Tropicast.Station.Audio.Windows.csproj" />
    <ProjectReference Include="..\Tropicast.Station.Audio.Linux\Tropicast.Station.Audio.Linux.csproj" />
    <ProjectReference Include="..\Tropicast.Station.Encoding\Tropicast.Station.Encoding.csproj" />
    <ProjectReference Include="..\Tropicast.Station.Infrastructure\Tropicast.Station.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tropicast.Station.App.Tests" />
  </ItemGroup>

</Project>
